/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasBanzos;

import Controller.ControladorAproveitamento;
import Utilitarios.ConexaoBanco;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author jejo
 */
public class TelaManterAproveitamento extends javax.swing.JFrame {
    ConexaoBanco conexao = new ConexaoBanco();
    ControladorAproveitamento CA = new ControladorAproveitamento();
    /**
     * Creates new form TelaNovoOrcamento
     */
    public TelaManterAproveitamento() {
        
        initComponents();
        listarAproveitamentos();
        listarComboTurmas();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("BanzosIcon.png")));//para setar um icone na janela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        comboTurmaAluno = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPesquisarAproveitamentos = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFrequencia = new javax.swing.JTextField();
        botaoSalvarAproveitamento = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbAproveitamento = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        checkbox10 = new java.awt.Checkbox();
        checkbox11 = new java.awt.Checkbox();
        checkbox12 = new java.awt.Checkbox();
        checkbox13 = new java.awt.Checkbox();
        checkbox16 = new java.awt.Checkbox();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboAluno = new javax.swing.JComboBox();
        botaoExcluir = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfis de Acesso");
        setMinimumSize(new java.awt.Dimension(805, 600));
        getContentPane().setLayout(null);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/find.png"))); // NOI18N
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton1.setRequestFocusEnabled(false);
        jToggleButton1.setRolloverEnabled(false);
        jToggleButton1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(70, 340, 30, 30);

        comboTurmaAluno.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        comboTurmaAluno.setToolTipText("M");
        comboTurmaAluno.setName("M"); // NOI18N
        comboTurmaAluno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTurmaAlunoItemStateChanged(evt);
            }
        });
        comboTurmaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboTurmaAlunoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboTurmaAlunoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboTurmaAlunoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboTurmaAlunoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboTurmaAlunoMouseReleased(evt);
            }
        });
        comboTurmaAluno.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                comboTurmaAlunoComponentHidden(evt);
            }
        });
        comboTurmaAluno.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                comboTurmaAlunoInputMethodTextChanged(evt);
            }
        });
        comboTurmaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTurmaAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(comboTurmaAluno);
        comboTurmaAluno.setBounds(370, 80, 220, 30);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 28)); // NOI18N
        jLabel1.setText("Aproveitamentos Cadastrados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 290, 400, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botton_banzos_icon2.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(670, 0, 130, 110);

        jLabel18.setText("Pesquisar");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 340, 60, 30);

        txtPesquisarAproveitamentos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtPesquisarAproveitamentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisarAproveitamentosKeyTyped(evt);
            }
        });
        getContentPane().add(txtPesquisarAproveitamentos);
        txtPesquisarAproveitamentos.setBounds(110, 340, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel5.setText("Novo Aproveitamento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 10, 340, 30);

        txtFrequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFrequenciaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFrequencia);
        txtFrequencia.setBounds(190, 130, 80, 30);

        botaoSalvarAproveitamento.setBackground(new java.awt.Color(0, 0, 0));
        botaoSalvarAproveitamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoSalvarAproveitamento.setForeground(new java.awt.Color(255, 255, 255));
        botaoSalvarAproveitamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/page_save.png"))); // NOI18N
        botaoSalvarAproveitamento.setText("Salvar");
        botaoSalvarAproveitamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                botaoSalvarAproveitamentoAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        botaoSalvarAproveitamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarAproveitamentoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSalvarAproveitamento);
        botaoSalvarAproveitamento.setBounds(240, 210, 110, 30);

        botaoCancelar.setBackground(new java.awt.Color(0, 0, 0));
        botaoCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel.png"))); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCancelar);
        botaoCancelar.setBounds(390, 210, 109, 30);

        jLabel6.setText("Frequência");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 130, 70, 20);

        jLabel7.setText("Nome Aluno");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 130, 80, 20);

        txtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNota);
        txtNota.setBounds(190, 80, 80, 30);

        tbAproveitamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbAproveitamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "João Paul", "80%", "80%", "Teórico Iniciante e Prático em Canto", null},
                {"002", "Gabriel Ricardo", "70%", "90%", "Teórico Iniciante e Prático em Violão", null},
                {"003", "Luana Alvez", "50%", "50%", "Teórico Intermediário e Prático em Violão", null},
                {"004", "Jessica Amorim", "60%", "70%", "Prático em Bateria", null},
                {"005", "Ricardo Lima", "90%", "100%", "Teórico Iniciante e Prático em Contrabaixo", null},
                {"006", "Paulo Augusto", "40%", "60%", "Teórico Iniciante", ""},
                {"007", "Lucas Neto", "80%", "70%", "Teórico Avançado e Prático em Piano", null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Nome", "Nota", "Frequência", "Turmas", "Opções"
            }
        ));
        jScrollPane4.setViewportView(tbAproveitamento);
        if (tbAproveitamento.getColumnModel().getColumnCount() > 0) {
            tbAproveitamento.getColumnModel().getColumn(0).setMinWidth(40);
            tbAproveitamento.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbAproveitamento.getColumnModel().getColumn(0).setMaxWidth(40);
            tbAproveitamento.getColumnModel().getColumn(1).setMinWidth(100);
            tbAproveitamento.getColumnModel().getColumn(1).setMaxWidth(100);
            tbAproveitamento.getColumnModel().getColumn(2).setMaxWidth(50);
            tbAproveitamento.getColumnModel().getColumn(3).setMaxWidth(80);
            tbAproveitamento.getColumnModel().getColumn(5).setMinWidth(150);
            tbAproveitamento.getColumnModel().getColumn(5).setPreferredWidth(150);
            tbAproveitamento.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(20, 380, 760, 140);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        checkbox10.setLabel("Teórica Iniciante A - Seg 8h, Qua 8h");
        jPanel2.add(checkbox10);
        checkbox10.setBounds(10, 0, 230, 20);

        checkbox11.setLabel("Prática Violão - Ter 8h, Qui 8h");
        jPanel2.add(checkbox11);
        checkbox11.setBounds(10, 20, 200, 20);

        checkbox12.setLabel("Teórica Intermediário A - Qua 10h, Sex 10h");
        jPanel2.add(checkbox12);
        checkbox12.setBounds(10, 40, 260, 20);

        checkbox13.setLabel("Prática Guitarra - Sex 10h, Dom 10h");
        jPanel2.add(checkbox13);
        checkbox13.setBounds(10, 80, 260, 20);

        checkbox16.setLabel("Prática Bateria - Ter 10h, Qui 10h");
        jPanel2.add(checkbox16);
        checkbox16.setBounds(10, 60, 200, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, -50, 0, 0);

        jLabel22.setText("Turma");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(320, 70, 40, 30);

        jLabel9.setText("Nota Aluno");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 80, 60, 20);

        jLabel12.setText("Aluno");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(130, 150, 40, 10);

        comboAluno.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        comboAluno.setToolTipText("M");
        comboAluno.setName("M"); // NOI18N
        comboAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboAlunoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboAlunoMouseEntered(evt);
            }
        });
        comboAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(comboAluno);
        comboAluno.setBounds(370, 130, 220, 30);

        botaoExcluir.setBackground(new java.awt.Color(0, 0, 0));
        botaoExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoExcluir.setForeground(new java.awt.Color(255, 255, 255));
        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(botaoExcluir);
        botaoExcluir.setBounds(670, 340, 110, 30);

        botaoAlterar.setBackground(new java.awt.Color(0, 0, 0));
        botaoAlterar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoAlterar.setForeground(new java.awt.Color(255, 255, 255));
        botaoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/page_attach.png"))); // NOI18N
        botaoAlterar.setText("Editar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAlterar);
        botaoAlterar.setBounds(530, 340, 110, 30);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Cadastrar");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        jMenuItem1.setText("Aluno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user_gray.png"))); // NOI18N
        jMenuItem2.setText("Funcionário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/page.png"))); // NOI18N
        jMenuItem3.setText("Aproveitamento");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/music.png"))); // NOI18N
        jMenuItem4.setText("Instrumento");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/group_key.png"))); // NOI18N
        jMenuItem5.setText("Perfil de Acesso");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/money_add.png"))); // NOI18N
        jMenuItem6.setText("Planos de Matrícula");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/group_add.png"))); // NOI18N
        jMenuItem7.setText("Turmas");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/money.png"))); // NOI18N
        jMenuItem8.setText("Situação de Pagamento");
        jMenu1.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user_orange.png"))); // NOI18N
        jMenuItem9.setText("Situação de Matrícula");
        jMenu1.add(jMenuItem9);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("|");
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Emitir");

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/page_attach.png"))); // NOI18N
        jMenuItem10.setText("Histórico Escolar");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/page_green.png"))); // NOI18N
        jMenuItem11.setText("Declaração");
        jMenu2.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/page_go.png"))); // NOI18N
        jMenuItem12.setText("Certificado");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.add(jSeparator2);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("|");
        jMenuBar1.add(jMenu5);

        jMenu3.setText("Relatório");

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/table.png"))); // NOI18N
        jMenuItem13.setText("Aproveitamento");
        jMenu3.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/group.png"))); // NOI18N
        jMenuItem14.setText("Turmas");
        jMenu3.add(jMenuItem14);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/group_gear.png"))); // NOI18N
        jMenuItem15.setText("Professores");
        jMenu3.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/music.png"))); // NOI18N
        jMenuItem16.setText("Alunos/Instrumentos");
        jMenu3.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/money_delete.png"))); // NOI18N
        jMenuItem17.setText("Alunos Inadimplentes");
        jMenu3.add(jMenuItem17);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar.png"))); // NOI18N
        jMenuItem18.setText("Alunos/Dia");
        jMenu3.add(jMenuItem18);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("|");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaActionPerformed

    private void txtFrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFrequenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFrequenciaActionPerformed

    private void comboAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAlunoActionPerformed

    private void comboTurmaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTurmaAlunoActionPerformed
         
    }//GEN-LAST:event_comboTurmaAlunoActionPerformed

    private void botaoSalvarAproveitamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarAproveitamentoActionPerformed
       String turma;
       String aluno = null;
       Double nota = null;
       Double frequencia = null;
        
//  Testa se os campos de nota e frequencia, os combos de aluno e turmas para ver se estão vazios   
        if(txtNota.getText().equals("") || txtFrequencia.getText().equals("") || comboAluno.getSelectedItem() == null || comboTurmaAluno.getSelectedItem() == null ){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
            
//  Se nem um campo estiver vazio..
        }else{
            turma = comboTurmaAluno.getSelectedItem().toString();
            aluno = comboAluno.getSelectedItem().toString();            
            nota = Double.parseDouble(txtNota.getText());
            frequencia = Double.parseDouble(txtFrequencia.getText());
            
            ControladorAproveitamento CA = new ControladorAproveitamento();  
            
//  Envia os parametros para o controlador inserir no BD
            CA.IncluirAproveitamento(turma, aluno, nota, frequencia);
        }
        
//  Atualizar tabela
       listarAproveitamentos();
    }//GEN-LAST:event_botaoSalvarAproveitamentoActionPerformed

    private void botaoSalvarAproveitamentoAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_botaoSalvarAproveitamentoAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalvarAproveitamentoAncestorMoved

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int[] L = tbAproveitamento.getSelectedRows();
        conexao.conecta();//inicia conexao com o BD   
         
        if (L.length == 1) {
            String mat = tbAproveitamento.getValueAt(L[0], 0)+"";  
            String turma = tbAproveitamento.getValueAt(L[0], 4)+""; 
            int m = Integer.parseInt(mat);
            int cod_turma_periodo = 0;
            
//  SQL para descobrir o código da tabela rl_turma_periodo referente a turma         
            String sql ="SELECT TP.cod_turma_periodo FROM rl_turma_periodo TP\n" +
                        "INNER JOIN tb_turma T\n" +
                        "ON TP.cod_turma = T.cod_turma\n" +
                        "WHERE turma = '"+turma+"'";
            try {
                conexao.SelectSQL(sql);
                conexao.rs.next();
                cod_turma_periodo = conexao.rs.getInt("cod_turma_periodo");
            } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(null, "Não foi possivel achar a turma!");
            }
            
//  DELETA da tabela rl_aluno_turma            
            sql = "DELETE FROM rl_aluno_turma WHERE matricula ="+m+" AND cod_turma_periodo ="+cod_turma_periodo;
            conexao.DeleteSQP(sql);  
            
            sql= "INSERT INTO rl_aluno_turma (matricula, cod_turma_periodo)\n" +
                    "VALUES("+m+","+cod_turma_periodo+")";
            conexao.ExecutaSQL(sql);            
        }
        
        conexao.desconecta();//fecha conexao com o BD
        limpaCampos();
        listarAproveitamentos();
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        limpaCampos();
        int[] L = tbAproveitamento.getSelectedRows();        
        try{
            txtNota.setText(tbAproveitamento.getValueAt(L[0], 2)+"");   
            txtFrequencia.setText(tbAproveitamento.getValueAt(L[0], 3)+"");
            comboTurmaAluno.setSelectedItem(tbAproveitamento.getValueAt(L[0], 4)+"");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Dados informados estão incorretos");
        }
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void comboTurmaAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTurmaAlunoMouseClicked
          comboAluno.removeAllItems();
    }//GEN-LAST:event_comboTurmaAlunoMouseClicked

    private void comboTurmaAlunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTurmaAlunoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTurmaAlunoMousePressed

    private void comboTurmaAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTurmaAlunoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTurmaAlunoMouseEntered

    private void comboTurmaAlunoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTurmaAlunoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTurmaAlunoMouseExited

    private void comboTurmaAlunoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTurmaAlunoMouseReleased
        
    }//GEN-LAST:event_comboTurmaAlunoMouseReleased

    private void comboTurmaAlunoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTurmaAlunoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTurmaAlunoItemStateChanged

    private void comboTurmaAlunoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_comboTurmaAlunoInputMethodTextChanged
        
    }//GEN-LAST:event_comboTurmaAlunoInputMethodTextChanged

    private void comboTurmaAlunoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_comboTurmaAlunoComponentHidden
        
    }//GEN-LAST:event_comboTurmaAlunoComponentHidden

    private void comboAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboAlunoMouseClicked
        
    }//GEN-LAST:event_comboAlunoMouseClicked

    private void comboAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboAlunoMouseEntered
       comboAluno.removeAllItems();
        conexao.conecta();
        int cod_turma = 0;
        String turma = comboTurmaAluno.getSelectedItem().toString();
        String sql = "SELECT cod_turma FROM tb_turma WHERE turma = '"+turma+"'";
        conexao.SelectSQL(sql);
        try {
            conexao.rs.next();
            cod_turma = Integer.parseInt(conexao.rs.getString("cod_turma"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel achar o código da turma");
        }
        
        sql= "SELECT A.nome FROM tb_aluno A\n" +
                    "INNER JOIN rl_aluno_turma AT\n" +
                    "ON A.matricula = AT.matricula\n" +
                    "INNER JOIN rl_turma_periodo TP\n" +
                    "ON AT.cod_turma_periodo = TP.cod_turma_periodo\n" +
                    "INNER JOIN tb_turma T\n" +
                    "ON TP.cod_turma = T.cod_turma\n"+
                    "WHERE T.cod_turma ="+cod_turma;
        
        conexao.SelectSQL(sql);        
        try {
            while (conexao.rs.next()) {                 
                comboAluno.addItem(conexao.rs.getString("nome")); 
            }
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error ao listar turmas! ");
        }       
        conexao.desconecta(); 
    }//GEN-LAST:event_comboAlunoMouseEntered

    private void txtPesquisarAproveitamentosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarAproveitamentosKeyTyped
        
//   PARA PESQUISAR OS CAMPOS DA TABELA     
        DefaultTableModel tabela_clientes = (DefaultTableModel) tbAproveitamento.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela_clientes);
        tbAproveitamento.setRowSorter(sorter);
        String text = txtPesquisarAproveitamentos.getText();
        if (text.length() == 0)
        {
            sorter.setRowFilter(null);
        }
        else
        {
            try
            {
                sorter.setRowFilter(
                    RowFilter.regexFilter(text));
            }
            catch (PatternSyntaxException pse)
            {
                System.err.println("Erro");
            }
        }
    }//GEN-LAST:event_txtPesquisarAproveitamentosKeyTyped

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
        TelaHomeGerente THG = new TelaHomeGerente();
        THG.setVisible(true);
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManterAproveitamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManterAproveitamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManterAproveitamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManterAproveitamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManterAproveitamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoSalvarAproveitamento;
    private java.awt.Checkbox checkbox10;
    private java.awt.Checkbox checkbox11;
    private java.awt.Checkbox checkbox12;
    private java.awt.Checkbox checkbox13;
    private java.awt.Checkbox checkbox16;
    private javax.swing.JComboBox comboAluno;
    private javax.swing.JComboBox comboTurmaAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tbAproveitamento;
    private javax.swing.JTextField txtFrequencia;
    private javax.swing.JTextField txtNota;
    private javax.swing.JFormattedTextField txtPesquisarAproveitamentos;
    // End of variables declaration//GEN-END:variables

    private void listarComboTurmas() {
        conexao.conecta();//inciacao conexao com o BD
        String sql= "SELECT T.turma FROM tb_turma T\n" +
                    "INNER JOIN rl_turma_periodo TP\n" +
                    "ON T.cod_turma = TP.cod_turma\n" +
                    "INNER JOIN rl_aluno_turma A\n" +
                    "ON TP.cod_turma_periodo = A.cod_turma_periodo";
        conexao.SelectSQL(sql);
         try {
            while (conexao.rs.next()) {
                comboTurmaAluno.addItem(conexao.rs.getString("turma"));
            }
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error ao listar combo de turmas! ");
        }
        conexao.desconecta();//fecha a conexao  
    }

    private void listarAproveitamentos() {
        conexao.conecta();//inciacao conexao com o BD
        conexao.SelectSQL("SELECT A.matricula, A.nome, RL.nota, RL.frequencia, T.turma \n" +
"                            FROM rl_aluno_turma RL \n" +
"                            INNER JOIN tb_aluno A \n" +
"                            ON RL.matricula = A.matricula \n" +
"                            INNER JOIN rl_turma_periodo TP  \n" +
"                            ON TP.cod_turma_periodo = RL.cod_turma_periodo \n" +
"                            INNER JOIN tb_turma T  \n" +
"                            ON TP.cod_turma = T.cod_turma\n" +
"                            WHERE nota != 0 \n"+                
"                            ORDER BY matricula ASC" );
        tbAproveitamento.setModel(DbUtils.resultSetToTableModel(conexao.rs));
        conexao.desconecta();//fecha a conexao com o BD
    }

    private void limpaCampos() {
       txtNota.setText("");
       txtFrequencia.setText("");
       comboAluno.removeAllItems();
    }
}
